version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
    env_file:
      - .env
    command: pytest --tb=short -q
