name: Trades Report

permissions:
  contents: read

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"  # daily at 06:00 UTC

env:
  UPLOAD_DIR: uploads
  REPORT_FILE: kraken_parsed_trades.xlsx
  DOCKER_IMAGE: krakentrades:latest
  SMTP_SERVER: smtp.gmail.com
  SMTP_PORT: 465
  EMAIL_SUBJECT: "Daily Kraken Trades Report"
  EMAIL_BODY: "Please find attached today's Kraken trades report."

jobs:
  build-and-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install pydrive2

      - name: Prepare upload directory
        run: mkdir -p ${{ env.UPLOAD_DIR }}

      - name: Download trades.pdf from Google Drive
        env:
          GOOGLE_DRIVE_JSON_KEY: ${{ secrets.GOOGLE_DRIVE_JSON_KEY }}
        run: python scripts/get_trades_pdf.py

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ${{ env.DOCKER_IMAGE }}
          load: true

      - name: Validate secrets
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          REPORT_RECIPIENT: ${{ secrets.REPORT_RECIPIENT }}
        run: |
          set -e
          for var in EMAIL_USER EMAIL_PASS REPORT_RECIPIENT; do
            if [ -z "${!var}" ]; then
              echo "ERROR: Secret $var is not defined!"
              exit 1
            fi
          done

      - name: Run Docker container to generate report
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/uploads:/app/uploads:rw \
            -e UPLOAD_DIR=/app/uploads \
            ${{ env.DOCKER_IMAGE }}


      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: kraken-trades
          path: ${{ env.UPLOAD_DIR }}/${{ env.REPORT_FILE }}

      - name: Send report by email
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ env.SMTP_SERVER }}
          server_port: ${{ env.SMTP_PORT }}
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: ${{ env.EMAIL_SUBJECT }}
          to: ${{ secrets.REPORT_RECIPIENT }}
          from: "Kraken Bot <${{ secrets.EMAIL_USER }}>"
          body: ${{ env.EMAIL_BODY }}
          attachments: ${{ env.UPLOAD_DIR }}/${{ env.REPORT_FILE }}
